Java/JRE/JDK-(8.0.162.12|9.0.4.11|10.0.0.46)-11:         * Support for Java 9/10                 * modified download                 * only 64 bit                 * fixed search pattern for uninstall         * spec files:                 * spec.json = generic Java/JRE/JDK                 * spec_java<major_release>.json = ProductId (Java|JRE|JDK)<major_release>         * readme.md updated         * make target "download" creates md5sums for archives         * check md5sums of archives in self download packages         * Makefile         		* support for opsi 4.1         		* option for alternative spec file                 *  fixes to consider various jre/jdk releases         * new properties:                 * auto_update                 * web_java_security_level                 * msi_silent_option                 * set_env_java_home                 * new property: uninstall_before_setup         * support for *.opsifunc in Makefile         * handling of JAVA_HOME and PATH (property)         * Makefile improvements, support for custom names (self download packages)         * logfile for preinst/postinst defined in spec         * streamlined postinst.in         * moved and modified: package_download.sh.in to product_downloader.sh.in         * Update to java8_8.0.162.12 / java9_9.0.4.11         * Update psdetail.exe 0.1.9.0.dev -> 0.1.10.0dev; debug version included         * Product_variables.opsiinc.in: testing packages using debug version of psdetail.exe         * control.in: description for kill_applic adjusted         * Fix in Makefile for download section         * Spec files adjusted         * .gitignore fixed for wanted executables         * fix control/product_variables to handle {{#ifdef}} for jre/jdk properties 		* some fixes for uninstaller, cosmetics 		* fix link name for local documentation 		* reduce loglevel when removing docs 		* optional: install documentation for JDK

diff --git a/SRC/OPSI/postinst.in b/SRC/OPSI/postinst.in
--- a/SRC/OPSI/postinst.in
+++ b/SRC/OPSI/postinst.in
@@ -1,24 +1,18 @@
 #! /bin/bash -x
 #=====================================================================
-# postinst script JAVA8
-# This script executes after unpacking files from that archive and registering the product at the depot.
+# postinst script JAVA/JRE/JDK
+# This script executes after unpacking files from that archive and
+# registering the product at the depot.
 #
-# The following environment variables can be used to obtain information about the current installation:
+# The following environment variables can be used to obtain information
+# about the current installation:
 #   PRODUCT_ID: id of the current product
 #   CLIENT_DATA_DIR: directory which contains the installed client data
 #=====================================================================
-# J. Boettge <boettge@mpi-halle.mpg.de>  2017-11-24 13:16:40 +0100
+# J. Boettge <boettge@mpi-halle.mpg.de>  2018-03-27 08:25:52 +0200
 #=====================================================================
 
-{{#ifdef_auto_download}}
-AUTO_DOWNLOAD="true"
-{{/ifdef_auto_download}}
-{{^ifdef_auto_download}}
-AUTO_DOWNLOAD="false"
-{{/ifdef_auto_download}}
-
-
-LOGFILE=/tmp/${PRODUCT_ID}__opsi_package_install.log
+LOGFILE={{O_INST_LOG}}
 
 exec >> $LOGFILE
 exec 2>&1
@@ -29,6 +23,17 @@ echo "=================================================="
 echo "${PRODUCT_ID} POSTINST LOG"
 echo "=================================================="
 
+PROD="{{O_BASE_JAVA}}"
+PROD=${PROD%%[0-9]*}
+VERSION={{O_SOFTWARE_VER}}
+J_RELEASE=${VERSION%%.*}
+SRC="${CLIENT_DATA_DIR}/../../source/${PROD}${J_RELEASE}"
+#SRC="${CLIENT_DATA_DIR}/../../source/${PRODUCT_ID##0_}"
+DST="${CLIENT_DATA_DIR}/files"
+# remove trailing "/" in path:
+DST=${DST%\/}
+ERR=0
+
 ### check for testing and DFN package:
 P=${PRODUCT_ID}
 [ "${P}" = "${P##0_}" -a "${P}" = "${P##test_}" ] &&  IS_TESTING=false || IS_TESTING=true
@@ -37,18 +42,11 @@ P=${P/#test_/}
 [ "${P}" = "${P##dfn_}" ] && IS_DFN=false || IS_DFN=true
 
 
-SRC="${CLIENT_DATA_DIR}/../../source/${PRODUCT_ID##0_}"
-DST="${CLIENT_DATA_DIR}/files"
-# remove trailing "/" in path:
-DST=${DST%\/}
-ERR=0
-
-
 if [ $IS_DFN == true ]; then
 	 [ ! -d "${DST}" ] && mkdir $DST
 else
-	### symlink files directory to ../../source/${PRODUCT_ID##0_} only
-	### for non-DFN packages:
+	### symlink files directory to ../../source/${PRODUCT_ID##0_}
+	### only for non-DFN packages:
 	if [ -h "${DST}" ]; then
 		echo "Symlink to [${DST}] already exists. - Replacing"
 		rm ${DST}
@@ -90,66 +88,17 @@ rm -rf $TMP_DIR
 
 
 {{^ifdef_allinc}}
-[ "${AUTO_DOWNLOAD}" != "true" ] && exit 0
-echo "Downloading files form vendor..."
-### download files form vendor:
-
-#VERSION=`opsi-admin -dS method getProduct_hash ${PRODUCT_ID} | grep productVersion | cut -d "=" -f 2`
-
-BASE="http://download.oracle.com/otn-pub/java/"
-JAVA_VER="{{JAVA_VER}}"
-JAVA_BUILD="{{JAVA_BUILD}}"
-HASH="{{HASH}}"
-
-JAVAFX_VER="{{JAVAFX_VER}}"
-JAVAFX_BLD="{{JAVAFX_BLD}}"
-JAVAFX_HASH="{{JAVAFX_HASH}}"
-
-CNT=0
-WGET_OPTS="--max-redirect=2 --no-cookies --header \"Cookie: oraclelicense=accept-securebackup-cookie\" "
-FS_THRESHOLD=10000
-
-download()
-{	
-	DL_URL=$1
-	[ -n "$2" ] && PACKAGE=$2 || PACKAGE=`basename $DL_URL`
-	
-	let "CNT++"
-	echo -e "Retrieving [$PACKAGE]\n\tfrom: [${DL_URL}]";
-	if [ -f "${DST}/${PACKAGE}" ]; then
-		echo -e "\tfile already exists"
-	else
-		eval wget ${WGET_OPTS} -nv "${DL_URL}" -O "${DST}/${PACKAGE}"
-		if  [ ! -f "${DST}/${PACKAGE}" ]; then
-			let "ERR+=1<<$CNT"
-		else
-			FILESIZE=$(stat -c%s "${DST}/${PACKAGE}")
-			if [ "${FS_THRESHOLD}" -gt "${FILESIZE}" ]; then
-				echo -e "*E*  file has an unusual size; assuming error page"
-				rm -f "${DST}/${PACKAGE}"
-				let "ERR+=1<<$CNT"
-			else			
-				chmod g+r "${DST}/${PACKAGE}"
-			fi
-		fi
-	fi	
-}
-
-{{#ifdef_property_jre}}
-download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}/${HASH}/jre-${JAVA_VER}-windows-x64.exe
-download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}/${HASH}/jre-${JAVA_VER}-windows-i586.exe
-{{/ifdef_property_jre}}
-
-{{#ifdef_property_jdk}}
-download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}/${HASH}/jdk-${JAVA_VER}-windows-x64.exe
-download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}/${HASH}/jdk-${JAVA_VER}-windows-i586.exe
-download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}/${HASH}/jdk-${JAVA_VER}-docs-all.zip
-{{/ifdef_property_jdk}}
-
-### the automatic download (currently) doesn't work for the demos and the javafx-apidocs
-# download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}-demos/${HASH}/jdk-${JAVA_VER}-windows-x64-demos.exe
-# download ${BASE}/jdk/${JAVA_VER}-${JAVA_BUILD}-demos/${HASH}/jdk-${JAVA_VER}-windows-i586-demos.exe
-# download ${BASE}/javafx/${JAVAFX_VER}-${JAVAFX_BLD}/${JAVAFX_HASH}/javafx-${JAVAFX_VER}-apidocs.zip
+{{#ifdef_auto_download}}
+### product downloader
+if [[ -f "${CLIENT_DATA_DIR}/product_downloader.sh" ]]; then
+	echo "Calling product downloader"
+	DEST_DIR=${DST} ${CLIENT_DATA_DIR}/product_downloader.sh
+	ERR=$?
+else
+	echo "Product downloader not found!"
+	ERR=2
+fi
+exit $ERR
+{{/ifdef_auto_download}}
 {{/ifdef_allinc}}
 
-exit $ERR
