{{O_BASE_JAVA}}-(8.0.181.13|10.0.2.13)-16: 	* product updates 	* restore custom directories in postinst improved

diff --git a/SRC/OPSI/postinst.in b/SRC/OPSI/postinst.in
--- a/SRC/OPSI/postinst.in
+++ b/SRC/OPSI/postinst.in
@@ -1,6 +1,7 @@
-#! /bin/bash -x
+#! /bin/bash
 #=====================================================================
 # postinst script JAVA/JRE/JDK
+#
 # This script executes after unpacking files from that archive and
 # registering the product at the depot.
 #
@@ -9,9 +10,10 @@
 #   PRODUCT_ID: id of the current product
 #   CLIENT_DATA_DIR: directory which contains the installed client data
 #=====================================================================
-# J. Boettge <boettge@mpi-halle.mpg.de>  2018-06-18 12:31:33 +0200
+# J. Boettge <boettge@mpi-halle.mpg.de>  2018-06-25 07:50:30 +0200
 #=====================================================================
 
+TS=$(date +"%s")
 LOGFILE={{O_INST_LOG}}
 
 exec >> $LOGFILE
@@ -20,8 +22,9 @@ chgrp opsiadmin $LOGFILE
 chmod g+rw $LOGFILE
 
 echo "=================================================="
-echo "${PRODUCT_ID} POSTINST LOG"
+echo "${PRODUCT_ID} ({{ORGNAME}}) POSTINST LOG"
 echo "=================================================="
+date +'Start: %F  %H:%M:%S'
 
 PROD="{{O_BASE_JAVA}}"
 PROD=${PROD%%[0-9]*}
@@ -77,8 +80,25 @@ if [ -d $TMP_DIR ]; then
 		if [ -d $TMP_DIR/${DIRNAME} ]; then
 			test -e $CLIENT_DATA_DIR/${DIRNAME} || mkdir $CLIENT_DATA_DIR/${DIRNAME}
 			echo -e "\tmoving $TMP_DIR/${DIRNAME} to $CLIENT_DATA_DIR/"
-			rsync -av --remove-source-files $TMP_DIR/${DIRNAME}/. $CLIENT_DATA_DIR/${DIRNAME}/ &&\
+			
+			IFS=$'\n'
+			PR=$TMP_DIR/${DIRNAME}
+			for D in `find ${PR} -xtype d`; do 
+				if [ -n "${D##${PR}}" -a ! -d "$CLIENT_DATA_DIR/${DIRNAME}/${D##${PR}}" ]; then
+					TGT=$CLIENT_DATA_DIR/${DIRNAME}/${D##${PR}}
+					echo -e "\t* mdir [${D##${PR}}] --> [${TGT}]"
+					mkdir -p "${TGT}"
+				fi
+			done &&\
+			for F in `find ${PR} -xtype f`; do
+				if [ -n "$F" -a ! -e "$CLIENT_DATA_DIR/${DIRNAME}/${F##${PR}/}" ]; then
+					echo -e "\t* fmov [${F##${PR}/}]"
+					mv "${F}" "$CLIENT_DATA_DIR/${DIRNAME}/${F##${PR}/}"
+				fi
+			done &&\
 			rm -rf $TMP_DIR/${DIRNAME} || exit 1
+			## rsync -av --remove-source-files $TMP_DIR/${DIRNAME}/. $CLIENT_DATA_DIR/${DIRNAME}/ && \
+			## rm -rf $TMP_DIR/${DIRNAME} || exit 1
 		else
 			echo -e "\tdoes not exist here"
 		fi
@@ -92,14 +112,17 @@ rm -rf $TMP_DIR
 {{#ifdef_auto_download}}
 ### product downloader
 if [[ -f "${CLIENT_DATA_DIR}/product_downloader.sh" ]]; then
-	echo "Calling product downloader"
+	echo -e "\nCalling product downloader"
 	DEST_DIR=${DST} ${CLIENT_DATA_DIR}/product_downloader.sh
 	ERR=$?
 else
-	echo "Product downloader not found!"
+	echo -e "\nProduct downloader not found!"
 	ERR=2
 fi
-exit $ERR
 {{/ifdef_auto_download}}
 {{/ifdef_allinc}}
 
+date +'Finish: %F  %H:%M:%S'
+TE=$(date +"%s")
+echo  "*** Script runtime: $(($TE - $TS)) seconds ***"
+exit $ERR
